version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    commands:
      - docker version
      - mkdir $HOME/.docker
      - nohup service docker start &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Bazel Build started on `date`
      - bazel run //worker/aws:worker_mp_aws_prod --sandbox_writable_path=$HOME/.docker --//worker/aws:ami_name_flag=aggregation-service-enclave_$(cat VERSION)  --//worker/aws:aws_region_flag=$AWS_DEFAULT_REGION
      - bash build-scripts/aws/set_ami_to_public.sh set_ami_to_public_by_prefix aggregation-service-enclave_$(cat VERSION) $AWS_DEFAULT_REGION $AWS_ACCOUNT_ID
      - cd build-scripts/aws && bash publish.sh
  post_build:
    commands:
      - echo Build completed on `date`

cache:
  paths:
    - '/root/.cache/bazel/**/*'
